// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void AcceptCallHandler(ReducerEventContext ctx, SpacetimeDB.Uuid sessionId);
        public event AcceptCallHandler? OnAcceptCall;

        public void AcceptCall(SpacetimeDB.Uuid sessionId)
        {
            conn.InternalCallReducer(new Reducer.AcceptCall(sessionId));
        }

        public bool InvokeAcceptCall(ReducerEventContext ctx, Reducer.AcceptCall args)
        {
            if (OnAcceptCall == null)
            {
                if (InternalOnUnhandledReducerError != null)
                {
                    switch (ctx.Event.Status)
                    {
                        case Status.Failed(var reason): InternalOnUnhandledReducerError(ctx, new Exception(reason)); break;
                        case Status.OutOfEnergy(var _): InternalOnUnhandledReducerError(ctx, new Exception("out of energy")); break;
                    }
                }
                return false;
            }
            OnAcceptCall(
                ctx,
                args.SessionId
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class AcceptCall : Reducer, IReducerArgs
        {
            [DataMember(Name = "session_id")]
            public SpacetimeDB.Uuid SessionId;

            public AcceptCall(SpacetimeDB.Uuid SessionId)
            {
                this.SessionId = SessionId;
            }

            public AcceptCall()
            {
            }

            string IReducerArgs.ReducerName => "accept_call";
        }
    }
}
