// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void CreateVoiceChannelHandler(ReducerEventContext ctx, string name, uint maxMembers);
        public event CreateVoiceChannelHandler? OnCreateVoiceChannel;

        public void CreateVoiceChannel(string name, uint maxMembers)
        {
            conn.InternalCallReducer(new Reducer.CreateVoiceChannel(name, maxMembers));
        }

        public bool InvokeCreateVoiceChannel(ReducerEventContext ctx, Reducer.CreateVoiceChannel args)
        {
            if (OnCreateVoiceChannel == null)
            {
                if (InternalOnUnhandledReducerError != null)
                {
                    switch (ctx.Event.Status)
                    {
                        case Status.Failed(var reason): InternalOnUnhandledReducerError(ctx, new Exception(reason)); break;
                        case Status.OutOfEnergy(var _): InternalOnUnhandledReducerError(ctx, new Exception("out of energy")); break;
                    }
                }
                return false;
            }
            OnCreateVoiceChannel(
                ctx,
                args.Name,
                args.MaxMembers
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class CreateVoiceChannel : Reducer, IReducerArgs
        {
            [DataMember(Name = "name")]
            public string Name;
            [DataMember(Name = "max_members")]
            public uint MaxMembers;

            public CreateVoiceChannel(
                string Name,
                uint MaxMembers
            )
            {
                this.Name = Name;
                this.MaxMembers = MaxMembers;
            }

            public CreateVoiceChannel()
            {
                this.Name = "";
            }

            string IReducerArgs.ReducerName => "create_voice_channel";
        }
    }
}
