// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void DeclineCallHandler(ReducerEventContext ctx, SpacetimeDB.Uuid sessionId);
        public event DeclineCallHandler? OnDeclineCall;

        public void DeclineCall(SpacetimeDB.Uuid sessionId)
        {
            conn.InternalCallReducer(new Reducer.DeclineCall(sessionId));
        }

        public bool InvokeDeclineCall(ReducerEventContext ctx, Reducer.DeclineCall args)
        {
            if (OnDeclineCall == null)
            {
                if (InternalOnUnhandledReducerError != null)
                {
                    switch (ctx.Event.Status)
                    {
                        case Status.Failed(var reason): InternalOnUnhandledReducerError(ctx, new Exception(reason)); break;
                        case Status.OutOfEnergy(var _): InternalOnUnhandledReducerError(ctx, new Exception("out of energy")); break;
                    }
                }
                return false;
            }
            OnDeclineCall(
                ctx,
                args.SessionId
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class DeclineCall : Reducer, IReducerArgs
        {
            [DataMember(Name = "session_id")]
            public SpacetimeDB.Uuid SessionId;

            public DeclineCall(SpacetimeDB.Uuid SessionId)
            {
                this.SessionId = SessionId;
            }

            public DeclineCall()
            {
            }

            string IReducerArgs.ReducerName => "decline_call";
        }
    }
}
