// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void DeleteVoiceChannelHandler(ReducerEventContext ctx, uint channelId);
        public event DeleteVoiceChannelHandler? OnDeleteVoiceChannel;

        public void DeleteVoiceChannel(uint channelId)
        {
            conn.InternalCallReducer(new Reducer.DeleteVoiceChannel(channelId));
        }

        public bool InvokeDeleteVoiceChannel(ReducerEventContext ctx, Reducer.DeleteVoiceChannel args)
        {
            if (OnDeleteVoiceChannel == null)
            {
                if (InternalOnUnhandledReducerError != null)
                {
                    switch (ctx.Event.Status)
                    {
                        case Status.Failed(var reason): InternalOnUnhandledReducerError(ctx, new Exception(reason)); break;
                        case Status.OutOfEnergy(var _): InternalOnUnhandledReducerError(ctx, new Exception("out of energy")); break;
                    }
                }
                return false;
            }
            OnDeleteVoiceChannel(
                ctx,
                args.ChannelId
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class DeleteVoiceChannel : Reducer, IReducerArgs
        {
            [DataMember(Name = "channel_id")]
            public uint ChannelId;

            public DeleteVoiceChannel(uint ChannelId)
            {
                this.ChannelId = ChannelId;
            }

            public DeleteVoiceChannel()
            {
            }

            string IReducerArgs.ReducerName => "delete_voice_channel";
        }
    }
}
