// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void LeaveVoiceChannelHandler(ReducerEventContext ctx);
        public event LeaveVoiceChannelHandler? OnLeaveVoiceChannel;

        public void LeaveVoiceChannel()
        {
            conn.InternalCallReducer(new Reducer.LeaveVoiceChannel());
        }

        public bool InvokeLeaveVoiceChannel(ReducerEventContext ctx, Reducer.LeaveVoiceChannel args)
        {
            if (OnLeaveVoiceChannel == null)
            {
                if (InternalOnUnhandledReducerError != null)
                {
                    switch (ctx.Event.Status)
                    {
                        case Status.Failed(var reason): InternalOnUnhandledReducerError(ctx, new Exception(reason)); break;
                        case Status.OutOfEnergy(var _): InternalOnUnhandledReducerError(ctx, new Exception("out of energy")); break;
                    }
                }
                return false;
            }
            OnLeaveVoiceChannel(
                ctx
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class LeaveVoiceChannel : Reducer, IReducerArgs
        {
            string IReducerArgs.ReducerName => "leave_voice_channel";
        }
    }
}
