// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void RequestCallHandler(ReducerEventContext ctx, SpacetimeDB.Identity target, SpacetimeDB.Types.CallType callType);
        public event RequestCallHandler? OnRequestCall;

        public void RequestCall(SpacetimeDB.Identity target, SpacetimeDB.Types.CallType callType)
        {
            conn.InternalCallReducer(new Reducer.RequestCall(target, callType));
        }

        public bool InvokeRequestCall(ReducerEventContext ctx, Reducer.RequestCall args)
        {
            if (OnRequestCall == null)
            {
                if (InternalOnUnhandledReducerError != null)
                {
                    switch (ctx.Event.Status)
                    {
                        case Status.Failed(var reason): InternalOnUnhandledReducerError(ctx, new Exception(reason)); break;
                        case Status.OutOfEnergy(var _): InternalOnUnhandledReducerError(ctx, new Exception("out of energy")); break;
                    }
                }
                return false;
            }
            OnRequestCall(
                ctx,
                args.Target,
                args.CallType
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class RequestCall : Reducer, IReducerArgs
        {
            [DataMember(Name = "target")]
            public SpacetimeDB.Identity Target;
            [DataMember(Name = "call_type")]
            public CallType CallType;

            public RequestCall(
                SpacetimeDB.Identity Target,
                CallType CallType
            )
            {
                this.Target = Target;
                this.CallType = CallType;
            }

            public RequestCall()
            {
            }

            string IReducerArgs.ReducerName => "request_call";
        }
    }
}
