// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void SaveAudioSettingsHandler(ReducerEventContext ctx, string? inputDeviceId, string? outputDeviceId, byte microphoneVolume, byte outputVolume, byte micSensitivity, bool hearSelf);
        public event SaveAudioSettingsHandler? OnSaveAudioSettings;

        public void SaveAudioSettings(string? inputDeviceId, string? outputDeviceId, byte microphoneVolume, byte outputVolume, byte micSensitivity, bool hearSelf)
        {
            conn.InternalCallReducer(new Reducer.SaveAudioSettings(inputDeviceId, outputDeviceId, microphoneVolume, outputVolume, micSensitivity, hearSelf));
        }

        public bool InvokeSaveAudioSettings(ReducerEventContext ctx, Reducer.SaveAudioSettings args)
        {
            if (OnSaveAudioSettings == null)
            {
                if (InternalOnUnhandledReducerError != null)
                {
                    switch (ctx.Event.Status)
                    {
                        case Status.Failed(var reason): InternalOnUnhandledReducerError(ctx, new Exception(reason)); break;
                        case Status.OutOfEnergy(var _): InternalOnUnhandledReducerError(ctx, new Exception("out of energy")); break;
                    }
                }
                return false;
            }
            OnSaveAudioSettings(
                ctx,
                args.InputDeviceId,
                args.OutputDeviceId,
                args.MicrophoneVolume,
                args.OutputVolume,
                args.MicSensitivity,
                args.HearSelf
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class SaveAudioSettings : Reducer, IReducerArgs
        {
            [DataMember(Name = "input_device_id")]
            public string? InputDeviceId;
            [DataMember(Name = "output_device_id")]
            public string? OutputDeviceId;
            [DataMember(Name = "microphone_volume")]
            public byte MicrophoneVolume;
            [DataMember(Name = "output_volume")]
            public byte OutputVolume;
            [DataMember(Name = "mic_sensitivity")]
            public byte MicSensitivity;
            [DataMember(Name = "hear_self")]
            public bool HearSelf;

            public SaveAudioSettings(
                string? InputDeviceId,
                string? OutputDeviceId,
                byte MicrophoneVolume,
                byte OutputVolume,
                byte MicSensitivity,
                bool HearSelf
            )
            {
                this.InputDeviceId = InputDeviceId;
                this.OutputDeviceId = OutputDeviceId;
                this.MicrophoneVolume = MicrophoneVolume;
                this.OutputVolume = OutputVolume;
                this.MicSensitivity = MicSensitivity;
                this.HearSelf = HearSelf;
            }

            public SaveAudioSettings()
            {
            }

            string IReducerArgs.ReducerName => "save_audio_settings";
        }
    }
}
