// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void SendAudioFrameHandler(ReducerEventContext ctx, SpacetimeDB.Uuid sessionId, SpacetimeDB.Identity to, uint seq, uint sampleRate, byte channels, float rms, System.Collections.Generic.List<byte> pcm16Le);
        public event SendAudioFrameHandler? OnSendAudioFrame;

        public void SendAudioFrame(SpacetimeDB.Uuid sessionId, SpacetimeDB.Identity to, uint seq, uint sampleRate, byte channels, float rms, System.Collections.Generic.List<byte> pcm16Le)
        {
            conn.InternalCallReducer(new Reducer.SendAudioFrame(sessionId, to, seq, sampleRate, channels, rms, pcm16Le));
        }

        public bool InvokeSendAudioFrame(ReducerEventContext ctx, Reducer.SendAudioFrame args)
        {
            if (OnSendAudioFrame == null)
            {
                if (InternalOnUnhandledReducerError != null)
                {
                    switch (ctx.Event.Status)
                    {
                        case Status.Failed(var reason): InternalOnUnhandledReducerError(ctx, new Exception(reason)); break;
                        case Status.OutOfEnergy(var _): InternalOnUnhandledReducerError(ctx, new Exception("out of energy")); break;
                    }
                }
                return false;
            }
            OnSendAudioFrame(
                ctx,
                args.SessionId,
                args.To,
                args.Seq,
                args.SampleRate,
                args.Channels,
                args.Rms,
                args.Pcm16Le
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class SendAudioFrame : Reducer, IReducerArgs
        {
            [DataMember(Name = "session_id")]
            public SpacetimeDB.Uuid SessionId;
            [DataMember(Name = "to")]
            public SpacetimeDB.Identity To;
            [DataMember(Name = "seq")]
            public uint Seq;
            [DataMember(Name = "sample_rate")]
            public uint SampleRate;
            [DataMember(Name = "channels")]
            public byte Channels;
            [DataMember(Name = "rms")]
            public float Rms;
            [DataMember(Name = "pcm_16_le")]
            public System.Collections.Generic.List<byte> Pcm16Le;

            public SendAudioFrame(
                SpacetimeDB.Uuid SessionId,
                SpacetimeDB.Identity To,
                uint Seq,
                uint SampleRate,
                byte Channels,
                float Rms,
                System.Collections.Generic.List<byte> Pcm16Le
            )
            {
                this.SessionId = SessionId;
                this.To = To;
                this.Seq = Seq;
                this.SampleRate = SampleRate;
                this.Channels = Channels;
                this.Rms = Rms;
                this.Pcm16Le = Pcm16Le;
            }

            public SendAudioFrame()
            {
                this.Pcm16Le = new();
            }

            string IReducerArgs.ReducerName => "send_audio_frame";
        }
    }
}
