// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void SendAudioFrameHandler(ReducerEventContext ctx, uint sequence, uint sampleRate, byte channels, float rms, System.Collections.Generic.List<byte> opusData);
        public event SendAudioFrameHandler? OnSendAudioFrame;

        public void SendAudioFrame(uint sequence, uint sampleRate, byte channels, float rms, System.Collections.Generic.List<byte> opusData)
        {
            conn.InternalCallReducer(new Reducer.SendAudioFrame(sequence, sampleRate, channels, rms, opusData));
        }

        public bool InvokeSendAudioFrame(ReducerEventContext ctx, Reducer.SendAudioFrame args)
        {
            if (OnSendAudioFrame == null)
            {
                if (InternalOnUnhandledReducerError != null)
                {
                    switch (ctx.Event.Status)
                    {
                        case Status.Failed(var reason): InternalOnUnhandledReducerError(ctx, new Exception(reason)); break;
                        case Status.OutOfEnergy(var _): InternalOnUnhandledReducerError(ctx, new Exception("out of energy")); break;
                    }
                }
                return false;
            }
            OnSendAudioFrame(
                ctx,
                args.Sequence,
                args.SampleRate,
                args.Channels,
                args.Rms,
                args.OpusData
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class SendAudioFrame : Reducer, IReducerArgs
        {
            [DataMember(Name = "sequence")]
            public uint Sequence;
            [DataMember(Name = "sample_rate")]
            public uint SampleRate;
            [DataMember(Name = "channels")]
            public byte Channels;
            [DataMember(Name = "rms")]
            public float Rms;
            [DataMember(Name = "opus_data")]
            public System.Collections.Generic.List<byte> OpusData;

            public SendAudioFrame(
                uint Sequence,
                uint SampleRate,
                byte Channels,
                float Rms,
                System.Collections.Generic.List<byte> OpusData
            )
            {
                this.Sequence = Sequence;
                this.SampleRate = SampleRate;
                this.Channels = Channels;
                this.Rms = Rms;
                this.OpusData = OpusData;
            }

            public SendAudioFrame()
            {
                this.OpusData = new();
            }

            string IReducerArgs.ReducerName => "send_audio_frame";
        }
    }
}
