// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void SendVideoFrameHandler(ReducerEventContext ctx, SpacetimeDB.Uuid sessionId, SpacetimeDB.Identity to, uint seq, ushort width, ushort height, System.Collections.Generic.List<byte> jpeg);
        public event SendVideoFrameHandler? OnSendVideoFrame;

        public void SendVideoFrame(SpacetimeDB.Uuid sessionId, SpacetimeDB.Identity to, uint seq, ushort width, ushort height, System.Collections.Generic.List<byte> jpeg)
        {
            conn.InternalCallReducer(new Reducer.SendVideoFrame(sessionId, to, seq, width, height, jpeg));
        }

        public bool InvokeSendVideoFrame(ReducerEventContext ctx, Reducer.SendVideoFrame args)
        {
            if (OnSendVideoFrame == null)
            {
                if (InternalOnUnhandledReducerError != null)
                {
                    switch (ctx.Event.Status)
                    {
                        case Status.Failed(var reason): InternalOnUnhandledReducerError(ctx, new Exception(reason)); break;
                        case Status.OutOfEnergy(var _): InternalOnUnhandledReducerError(ctx, new Exception("out of energy")); break;
                    }
                }
                return false;
            }
            OnSendVideoFrame(
                ctx,
                args.SessionId,
                args.To,
                args.Seq,
                args.Width,
                args.Height,
                args.Jpeg
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class SendVideoFrame : Reducer, IReducerArgs
        {
            [DataMember(Name = "session_id")]
            public SpacetimeDB.Uuid SessionId;
            [DataMember(Name = "to")]
            public SpacetimeDB.Identity To;
            [DataMember(Name = "seq")]
            public uint Seq;
            [DataMember(Name = "width")]
            public ushort Width;
            [DataMember(Name = "height")]
            public ushort Height;
            [DataMember(Name = "jpeg")]
            public System.Collections.Generic.List<byte> Jpeg;

            public SendVideoFrame(
                SpacetimeDB.Uuid SessionId,
                SpacetimeDB.Identity To,
                uint Seq,
                ushort Width,
                ushort Height,
                System.Collections.Generic.List<byte> Jpeg
            )
            {
                this.SessionId = SessionId;
                this.To = To;
                this.Seq = Seq;
                this.Width = Width;
                this.Height = Height;
                this.Jpeg = Jpeg;
            }

            public SendVideoFrame()
            {
                this.Jpeg = new();
            }

            string IReducerArgs.ReducerName => "send_video_frame";
        }
    }
}
