// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void SetUserVolumeHandler(ReducerEventContext ctx, SpacetimeDB.Identity targetUser, byte volume);
        public event SetUserVolumeHandler? OnSetUserVolume;

        public void SetUserVolume(SpacetimeDB.Identity targetUser, byte volume)
        {
            conn.InternalCallReducer(new Reducer.SetUserVolume(targetUser, volume));
        }

        public bool InvokeSetUserVolume(ReducerEventContext ctx, Reducer.SetUserVolume args)
        {
            if (OnSetUserVolume == null)
            {
                if (InternalOnUnhandledReducerError != null)
                {
                    switch (ctx.Event.Status)
                    {
                        case Status.Failed(var reason): InternalOnUnhandledReducerError(ctx, new Exception(reason)); break;
                        case Status.OutOfEnergy(var _): InternalOnUnhandledReducerError(ctx, new Exception("out of energy")); break;
                    }
                }
                return false;
            }
            OnSetUserVolume(
                ctx,
                args.TargetUser,
                args.Volume
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class SetUserVolume : Reducer, IReducerArgs
        {
            [DataMember(Name = "target_user")]
            public SpacetimeDB.Identity TargetUser;
            [DataMember(Name = "volume")]
            public byte Volume;

            public SetUserVolume(
                SpacetimeDB.Identity TargetUser,
                byte Volume
            )
            {
                this.TargetUser = TargetUser;
                this.Volume = Volume;
            }

            public SetUserVolume()
            {
            }

            string IReducerArgs.ReducerName => "set_user_volume";
        }
    }
}
