// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void SetVoiceMutedHandler(ReducerEventContext ctx, bool muted);
        public event SetVoiceMutedHandler? OnSetVoiceMuted;

        public void SetVoiceMuted(bool muted)
        {
            conn.InternalCallReducer(new Reducer.SetVoiceMuted(muted));
        }

        public bool InvokeSetVoiceMuted(ReducerEventContext ctx, Reducer.SetVoiceMuted args)
        {
            if (OnSetVoiceMuted == null)
            {
                if (InternalOnUnhandledReducerError != null)
                {
                    switch (ctx.Event.Status)
                    {
                        case Status.Failed(var reason): InternalOnUnhandledReducerError(ctx, new Exception(reason)); break;
                        case Status.OutOfEnergy(var _): InternalOnUnhandledReducerError(ctx, new Exception("out of energy")); break;
                    }
                }
                return false;
            }
            OnSetVoiceMuted(
                ctx,
                args.Muted
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class SetVoiceMuted : Reducer, IReducerArgs
        {
            [DataMember(Name = "muted")]
            public bool Muted;

            public SetVoiceMuted(bool Muted)
            {
                this.Muted = Muted;
            }

            public SetVoiceMuted()
            {
            }

            string IReducerArgs.ReducerName => "set_voice_muted";
        }
    }
}
