// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void SetVoiceDeafenedHandler(ReducerEventContext ctx, bool deafened);
        public event SetVoiceDeafenedHandler? OnSetVoiceDeafened;

        public void SetVoiceDeafened(bool deafened)
        {
            conn.InternalCallReducer(new Reducer.SetVoiceDeafened(deafened));
        }

        public bool InvokeSetVoiceDeafened(ReducerEventContext ctx, Reducer.SetVoiceDeafened args)
        {
            if (OnSetVoiceDeafened == null)
            {
                if (InternalOnUnhandledReducerError != null)
                {
                    switch (ctx.Event.Status)
                    {
                        case Status.Failed(var reason): InternalOnUnhandledReducerError(ctx, new Exception(reason)); break;
                        case Status.OutOfEnergy(var _): InternalOnUnhandledReducerError(ctx, new Exception("out of energy")); break;
                    }
                }
                return false;
            }
            OnSetVoiceDeafened(
                ctx,
                args.Deafened
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class SetVoiceDeafened : Reducer, IReducerArgs
        {
            [DataMember(Name = "deafened")]
            public bool Deafened;

            public SetVoiceDeafened(bool Deafened)
            {
                this.Deafened = Deafened;
            }

            public SetVoiceDeafened()
            {
            }

            string IReducerArgs.ReducerName => "set_voice_deafened";
        }
    }
}
