// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class AudioFrameEvent
    {
        [DataMember(Name = "channel_id")]
        public uint ChannelId;
        [DataMember(Name = "from_user")]
        public SpacetimeDB.Identity FromUser;
        [DataMember(Name = "sequence")]
        public uint Sequence;
        [DataMember(Name = "sample_rate")]
        public uint SampleRate;
        [DataMember(Name = "channels")]
        public byte Channels;
        [DataMember(Name = "rms")]
        public float Rms;
        [DataMember(Name = "opus_data")]
        public System.Collections.Generic.List<byte> OpusData;

        public AudioFrameEvent(
            uint ChannelId,
            SpacetimeDB.Identity FromUser,
            uint Sequence,
            uint SampleRate,
            byte Channels,
            float Rms,
            System.Collections.Generic.List<byte> OpusData
        )
        {
            this.ChannelId = ChannelId;
            this.FromUser = FromUser;
            this.Sequence = Sequence;
            this.SampleRate = SampleRate;
            this.Channels = Channels;
            this.Rms = Rms;
            this.OpusData = OpusData;
        }

        public AudioFrameEvent()
        {
            this.OpusData = new();
        }
    }
}
