// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class AudioFrameEvent
    {
        [DataMember(Name = "session_id")]
        public SpacetimeDB.Uuid SessionId;
        [DataMember(Name = "from")]
        public SpacetimeDB.Identity From;
        [DataMember(Name = "to")]
        public SpacetimeDB.Identity To;
        [DataMember(Name = "seq")]
        public uint Seq;
        [DataMember(Name = "sample_rate")]
        public uint SampleRate;
        [DataMember(Name = "channels")]
        public byte Channels;
        [DataMember(Name = "rms")]
        public float Rms;
        [DataMember(Name = "pcm_16_le")]
        public System.Collections.Generic.List<byte> Pcm16Le;

        public AudioFrameEvent(
            SpacetimeDB.Uuid SessionId,
            SpacetimeDB.Identity From,
            SpacetimeDB.Identity To,
            uint Seq,
            uint SampleRate,
            byte Channels,
            float Rms,
            System.Collections.Generic.List<byte> Pcm16Le
        )
        {
            this.SessionId = SessionId;
            this.From = From;
            this.To = To;
            this.Seq = Seq;
            this.SampleRate = SampleRate;
            this.Channels = Channels;
            this.Rms = Rms;
            this.Pcm16Le = Pcm16Le;
        }

        public AudioFrameEvent()
        {
            this.Pcm16Le = new();
        }
    }
}
