// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class CallSession
    {
        [DataMember(Name = "session_id")]
        public SpacetimeDB.Uuid SessionId;
        [DataMember(Name = "call_type")]
        public CallType CallType;
        [DataMember(Name = "state")]
        public CallState State;
        [DataMember(Name = "caller")]
        public SpacetimeDB.Identity Caller;
        [DataMember(Name = "callee")]
        public SpacetimeDB.Identity Callee;
        [DataMember(Name = "created_at")]
        public SpacetimeDB.Timestamp CreatedAt;
        [DataMember(Name = "answered_at")]
        public SpacetimeDB.Timestamp? AnsweredAt;

        public CallSession(
            SpacetimeDB.Uuid SessionId,
            CallType CallType,
            CallState State,
            SpacetimeDB.Identity Caller,
            SpacetimeDB.Identity Callee,
            SpacetimeDB.Timestamp CreatedAt,
            SpacetimeDB.Timestamp? AnsweredAt
        )
        {
            this.SessionId = SessionId;
            this.CallType = CallType;
            this.State = State;
            this.Caller = Caller;
            this.Callee = Callee;
            this.CreatedAt = CreatedAt;
            this.AnsweredAt = AnsweredAt;
        }

        public CallSession()
        {
        }
    }
}
