// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class MediaSettings
    {
        [DataMember(Name = "id")]
        public uint Id;
        [DataMember(Name = "audio_target_sample_rate")]
        public uint AudioTargetSampleRate;
        [DataMember(Name = "audio_frame_ms")]
        public ushort AudioFrameMs;
        [DataMember(Name = "audio_max_frame_bytes")]
        public uint AudioMaxFrameBytes;
        [DataMember(Name = "audio_talking_rms_threshold")]
        public float AudioTalkingRmsThreshold;
        [DataMember(Name = "video_width")]
        public ushort VideoWidth;
        [DataMember(Name = "video_height")]
        public ushort VideoHeight;
        [DataMember(Name = "video_fps")]
        public byte VideoFps;
        [DataMember(Name = "video_jpeg_quality")]
        public float VideoJpegQuality;
        [DataMember(Name = "video_max_frame_bytes")]
        public uint VideoMaxFrameBytes;

        public MediaSettings(
            uint Id,
            uint AudioTargetSampleRate,
            ushort AudioFrameMs,
            uint AudioMaxFrameBytes,
            float AudioTalkingRmsThreshold,
            ushort VideoWidth,
            ushort VideoHeight,
            byte VideoFps,
            float VideoJpegQuality,
            uint VideoMaxFrameBytes
        )
        {
            this.Id = Id;
            this.AudioTargetSampleRate = AudioTargetSampleRate;
            this.AudioFrameMs = AudioFrameMs;
            this.AudioMaxFrameBytes = AudioMaxFrameBytes;
            this.AudioTalkingRmsThreshold = AudioTalkingRmsThreshold;
            this.VideoWidth = VideoWidth;
            this.VideoHeight = VideoHeight;
            this.VideoFps = VideoFps;
            this.VideoJpegQuality = VideoJpegQuality;
            this.VideoMaxFrameBytes = VideoMaxFrameBytes;
        }

        public MediaSettings()
        {
        }
    }
}
