// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class User
    {
        [DataMember(Name = "identity")]
        public SpacetimeDB.Identity Identity;
        [DataMember(Name = "nickname")]
        public string Nickname;
        [DataMember(Name = "connected_at")]
        public SpacetimeDB.Timestamp ConnectedAt;

        public User(
            SpacetimeDB.Identity Identity,
            string Nickname,
            SpacetimeDB.Timestamp ConnectedAt
        )
        {
            this.Identity = Identity;
            this.Nickname = Nickname;
            this.ConnectedAt = ConnectedAt;
        }

        public User()
        {
            this.Nickname = "";
        }
    }
}
