// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class UserVolumeSettings
    {
        [DataMember(Name = "id")]
        public uint Id;
        [DataMember(Name = "user_id")]
        public SpacetimeDB.Identity UserId;
        [DataMember(Name = "target_user_id")]
        public SpacetimeDB.Identity TargetUserId;
        [DataMember(Name = "volume")]
        public byte Volume;

        public UserVolumeSettings(
            uint Id,
            SpacetimeDB.Identity UserId,
            SpacetimeDB.Identity TargetUserId,
            byte Volume
        )
        {
            this.Id = Id;
            this.UserId = UserId;
            this.TargetUserId = TargetUserId;
            this.Volume = Volume;
        }

        public UserVolumeSettings()
        {
        }
    }
}
