// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class UserAudioSettings
    {
        [DataMember(Name = "user_id")]
        public SpacetimeDB.Identity UserId;
        [DataMember(Name = "input_device_id")]
        public string? InputDeviceId;
        [DataMember(Name = "output_device_id")]
        public string? OutputDeviceId;
        [DataMember(Name = "microphone_volume")]
        public byte MicrophoneVolume;
        [DataMember(Name = "output_volume")]
        public byte OutputVolume;
        [DataMember(Name = "mic_sensitivity")]
        public byte MicSensitivity;
        [DataMember(Name = "hear_self")]
        public bool HearSelf;

        public UserAudioSettings(
            SpacetimeDB.Identity UserId,
            string? InputDeviceId,
            string? OutputDeviceId,
            byte MicrophoneVolume,
            byte OutputVolume,
            byte MicSensitivity,
            bool HearSelf
        )
        {
            this.UserId = UserId;
            this.InputDeviceId = InputDeviceId;
            this.OutputDeviceId = OutputDeviceId;
            this.MicrophoneVolume = MicrophoneVolume;
            this.OutputVolume = OutputVolume;
            this.MicSensitivity = MicSensitivity;
            this.HearSelf = HearSelf;
        }

        public UserAudioSettings()
        {
        }
    }
}
