// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class VideoFrameEvent
    {
        [DataMember(Name = "session_id")]
        public SpacetimeDB.Uuid SessionId;
        [DataMember(Name = "from")]
        public SpacetimeDB.Identity From;
        [DataMember(Name = "to")]
        public SpacetimeDB.Identity To;
        [DataMember(Name = "seq")]
        public uint Seq;
        [DataMember(Name = "width")]
        public ushort Width;
        [DataMember(Name = "height")]
        public ushort Height;
        [DataMember(Name = "jpeg")]
        public System.Collections.Generic.List<byte> Jpeg;

        public VideoFrameEvent(
            SpacetimeDB.Uuid SessionId,
            SpacetimeDB.Identity From,
            SpacetimeDB.Identity To,
            uint Seq,
            ushort Width,
            ushort Height,
            System.Collections.Generic.List<byte> Jpeg
        )
        {
            this.SessionId = SessionId;
            this.From = From;
            this.To = To;
            this.Seq = Seq;
            this.Width = Width;
            this.Height = Height;
            this.Jpeg = Jpeg;
        }

        public VideoFrameEvent()
        {
            this.Jpeg = new();
        }
    }
}
