// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class VoiceChannel
    {
        [DataMember(Name = "id")]
        public uint Id;
        [DataMember(Name = "name")]
        public string Name;
        [DataMember(Name = "max_members")]
        public uint MaxMembers;
        [DataMember(Name = "created_at")]
        public SpacetimeDB.Timestamp CreatedAt;
        [DataMember(Name = "created_by")]
        public SpacetimeDB.Identity CreatedBy;

        public VoiceChannel(
            uint Id,
            string Name,
            uint MaxMembers,
            SpacetimeDB.Timestamp CreatedAt,
            SpacetimeDB.Identity CreatedBy
        )
        {
            this.Id = Id;
            this.Name = Name;
            this.MaxMembers = MaxMembers;
            this.CreatedAt = CreatedAt;
            this.CreatedBy = CreatedBy;
        }

        public VoiceChannel()
        {
            this.Name = "";
        }
    }
}
