// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class VoiceChannelMember
    {
        [DataMember(Name = "user_id")]
        public SpacetimeDB.Identity UserId;
        [DataMember(Name = "channel_id")]
        public uint ChannelId;
        [DataMember(Name = "is_muted")]
        public bool IsMuted;
        [DataMember(Name = "is_deafened")]
        public bool IsDeafened;
        [DataMember(Name = "joined_at")]
        public SpacetimeDB.Timestamp JoinedAt;

        public VoiceChannelMember(
            SpacetimeDB.Identity UserId,
            uint ChannelId,
            bool IsMuted,
            bool IsDeafened,
            SpacetimeDB.Timestamp JoinedAt
        )
        {
            this.UserId = UserId;
            this.ChannelId = ChannelId;
            this.IsMuted = IsMuted;
            this.IsDeafened = IsDeafened;
            this.JoinedAt = JoinedAt;
        }

        public VoiceChannelMember()
        {
        }
    }
}
