// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.BSATN;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteTables
    {
        public sealed class AudioFrameEventHandle : RemoteEventTableHandle<EventContext, AudioFrameEvent>
        {
            protected override string RemoteTableName => "audio_frame_event";

            internal AudioFrameEventHandle(DbConnection conn) : base(conn)
            {
            }
        }

        public readonly AudioFrameEventHandle AudioFrameEvent;
    }

    public sealed class AudioFrameEventCols
    {
        public global::SpacetimeDB.Col<AudioFrameEvent, uint> ChannelId { get; }
        public global::SpacetimeDB.Col<AudioFrameEvent, SpacetimeDB.Identity> FromUser { get; }
        public global::SpacetimeDB.Col<AudioFrameEvent, uint> Sequence { get; }
        public global::SpacetimeDB.Col<AudioFrameEvent, uint> SampleRate { get; }
        public global::SpacetimeDB.Col<AudioFrameEvent, byte> Channels { get; }
        public global::SpacetimeDB.Col<AudioFrameEvent, float> Rms { get; }
        public global::SpacetimeDB.Col<AudioFrameEvent, System.Collections.Generic.List<byte>> OpusData { get; }

        public AudioFrameEventCols(string tableName)
        {
            ChannelId = new global::SpacetimeDB.Col<AudioFrameEvent, uint>(tableName, "channel_id");
            FromUser = new global::SpacetimeDB.Col<AudioFrameEvent, SpacetimeDB.Identity>(tableName, "from_user");
            Sequence = new global::SpacetimeDB.Col<AudioFrameEvent, uint>(tableName, "sequence");
            SampleRate = new global::SpacetimeDB.Col<AudioFrameEvent, uint>(tableName, "sample_rate");
            Channels = new global::SpacetimeDB.Col<AudioFrameEvent, byte>(tableName, "channels");
            Rms = new global::SpacetimeDB.Col<AudioFrameEvent, float>(tableName, "rms");
            OpusData = new global::SpacetimeDB.Col<AudioFrameEvent, System.Collections.Generic.List<byte>>(tableName, "opus_data");
        }
    }

    public sealed class AudioFrameEventIxCols
    {

        public AudioFrameEventIxCols(string tableName)
        {
        }
    }
}
