// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.BSATN;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteTables
    {
        public sealed class AudioFrameEventHandle : RemoteEventTableHandle<EventContext, AudioFrameEvent>
        {
            protected override string RemoteTableName => "audio_frame_event";

            internal AudioFrameEventHandle(DbConnection conn) : base(conn)
            {
            }
        }

        public readonly AudioFrameEventHandle AudioFrameEvent;
    }

    public sealed class AudioFrameEventCols
    {
        public global::SpacetimeDB.Col<AudioFrameEvent, SpacetimeDB.Uuid> SessionId { get; }
        public global::SpacetimeDB.Col<AudioFrameEvent, SpacetimeDB.Identity> From { get; }
        public global::SpacetimeDB.Col<AudioFrameEvent, SpacetimeDB.Identity> To { get; }
        public global::SpacetimeDB.Col<AudioFrameEvent, uint> Seq { get; }
        public global::SpacetimeDB.Col<AudioFrameEvent, uint> SampleRate { get; }
        public global::SpacetimeDB.Col<AudioFrameEvent, byte> Channels { get; }
        public global::SpacetimeDB.Col<AudioFrameEvent, float> Rms { get; }
        public global::SpacetimeDB.Col<AudioFrameEvent, System.Collections.Generic.List<byte>> Pcm16Le { get; }

        public AudioFrameEventCols(string tableName)
        {
            SessionId = new global::SpacetimeDB.Col<AudioFrameEvent, SpacetimeDB.Uuid>(tableName, "session_id");
            From = new global::SpacetimeDB.Col<AudioFrameEvent, SpacetimeDB.Identity>(tableName, "from");
            To = new global::SpacetimeDB.Col<AudioFrameEvent, SpacetimeDB.Identity>(tableName, "to");
            Seq = new global::SpacetimeDB.Col<AudioFrameEvent, uint>(tableName, "seq");
            SampleRate = new global::SpacetimeDB.Col<AudioFrameEvent, uint>(tableName, "sample_rate");
            Channels = new global::SpacetimeDB.Col<AudioFrameEvent, byte>(tableName, "channels");
            Rms = new global::SpacetimeDB.Col<AudioFrameEvent, float>(tableName, "rms");
            Pcm16Le = new global::SpacetimeDB.Col<AudioFrameEvent, System.Collections.Generic.List<byte>>(tableName, "pcm_16_le");
        }
    }

    public sealed class AudioFrameEventIxCols
    {

        public AudioFrameEventIxCols(string tableName)
        {
        }
    }
}
