// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.BSATN;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteTables
    {
        public sealed class CallSessionHandle : RemoteTableHandle<EventContext, CallSession>
        {
            protected override string RemoteTableName => "call_session";

            public sealed class SessionIdUniqueIndex : UniqueIndexBase<SpacetimeDB.Uuid>
            {
                protected override SpacetimeDB.Uuid GetKey(CallSession row) => row.SessionId;

                public SessionIdUniqueIndex(CallSessionHandle table) : base(table) { }
            }

            public readonly SessionIdUniqueIndex SessionId;

            internal CallSessionHandle(DbConnection conn) : base(conn)
            {
                SessionId = new(this);
            }

            protected override object GetPrimaryKey(CallSession row) => row.SessionId;
        }

        public readonly CallSessionHandle CallSession;
    }

    public sealed class CallSessionCols
    {
        public global::SpacetimeDB.Col<CallSession, SpacetimeDB.Uuid> SessionId { get; }
        public global::SpacetimeDB.Col<CallSession, CallType> CallType { get; }
        public global::SpacetimeDB.Col<CallSession, CallState> State { get; }
        public global::SpacetimeDB.Col<CallSession, SpacetimeDB.Identity> Caller { get; }
        public global::SpacetimeDB.Col<CallSession, SpacetimeDB.Identity> Callee { get; }
        public global::SpacetimeDB.Col<CallSession, SpacetimeDB.Timestamp> CreatedAt { get; }
        public global::SpacetimeDB.NullableCol<CallSession, SpacetimeDB.Timestamp> AnsweredAt { get; }

        public CallSessionCols(string tableName)
        {
            SessionId = new global::SpacetimeDB.Col<CallSession, SpacetimeDB.Uuid>(tableName, "session_id");
            CallType = new global::SpacetimeDB.Col<CallSession, CallType>(tableName, "call_type");
            State = new global::SpacetimeDB.Col<CallSession, CallState>(tableName, "state");
            Caller = new global::SpacetimeDB.Col<CallSession, SpacetimeDB.Identity>(tableName, "caller");
            Callee = new global::SpacetimeDB.Col<CallSession, SpacetimeDB.Identity>(tableName, "callee");
            CreatedAt = new global::SpacetimeDB.Col<CallSession, SpacetimeDB.Timestamp>(tableName, "created_at");
            AnsweredAt = new global::SpacetimeDB.NullableCol<CallSession, SpacetimeDB.Timestamp>(tableName, "answered_at");
        }
    }

    public sealed class CallSessionIxCols
    {
        public global::SpacetimeDB.IxCol<CallSession, SpacetimeDB.Uuid> SessionId { get; }

        public CallSessionIxCols(string tableName)
        {
            SessionId = new global::SpacetimeDB.IxCol<CallSession, SpacetimeDB.Uuid>(tableName, "session_id");
        }
    }
}
