// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.BSATN;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteTables
    {
        public sealed class MediaSettingsHandle : RemoteTableHandle<EventContext, MediaSettings>
        {
            protected override string RemoteTableName => "media_settings";

            public sealed class IdUniqueIndex : UniqueIndexBase<uint>
            {
                protected override uint GetKey(MediaSettings row) => row.Id;

                public IdUniqueIndex(MediaSettingsHandle table) : base(table) { }
            }

            public readonly IdUniqueIndex Id;

            internal MediaSettingsHandle(DbConnection conn) : base(conn)
            {
                Id = new(this);
            }

            protected override object GetPrimaryKey(MediaSettings row) => row.Id;
        }

        public readonly MediaSettingsHandle MediaSettings;
    }

    public sealed class MediaSettingsCols
    {
        public global::SpacetimeDB.Col<MediaSettings, uint> Id { get; }
        public global::SpacetimeDB.Col<MediaSettings, uint> AudioTargetSampleRate { get; }
        public global::SpacetimeDB.Col<MediaSettings, ushort> AudioFrameMs { get; }
        public global::SpacetimeDB.Col<MediaSettings, uint> AudioMaxFrameBytes { get; }
        public global::SpacetimeDB.Col<MediaSettings, float> AudioTalkingRmsThreshold { get; }
        public global::SpacetimeDB.Col<MediaSettings, ushort> VideoWidth { get; }
        public global::SpacetimeDB.Col<MediaSettings, ushort> VideoHeight { get; }
        public global::SpacetimeDB.Col<MediaSettings, byte> VideoFps { get; }
        public global::SpacetimeDB.Col<MediaSettings, float> VideoJpegQuality { get; }
        public global::SpacetimeDB.Col<MediaSettings, uint> VideoMaxFrameBytes { get; }

        public MediaSettingsCols(string tableName)
        {
            Id = new global::SpacetimeDB.Col<MediaSettings, uint>(tableName, "id");
            AudioTargetSampleRate = new global::SpacetimeDB.Col<MediaSettings, uint>(tableName, "audio_target_sample_rate");
            AudioFrameMs = new global::SpacetimeDB.Col<MediaSettings, ushort>(tableName, "audio_frame_ms");
            AudioMaxFrameBytes = new global::SpacetimeDB.Col<MediaSettings, uint>(tableName, "audio_max_frame_bytes");
            AudioTalkingRmsThreshold = new global::SpacetimeDB.Col<MediaSettings, float>(tableName, "audio_talking_rms_threshold");
            VideoWidth = new global::SpacetimeDB.Col<MediaSettings, ushort>(tableName, "video_width");
            VideoHeight = new global::SpacetimeDB.Col<MediaSettings, ushort>(tableName, "video_height");
            VideoFps = new global::SpacetimeDB.Col<MediaSettings, byte>(tableName, "video_fps");
            VideoJpegQuality = new global::SpacetimeDB.Col<MediaSettings, float>(tableName, "video_jpeg_quality");
            VideoMaxFrameBytes = new global::SpacetimeDB.Col<MediaSettings, uint>(tableName, "video_max_frame_bytes");
        }
    }

    public sealed class MediaSettingsIxCols
    {
        public global::SpacetimeDB.IxCol<MediaSettings, uint> Id { get; }

        public MediaSettingsIxCols(string tableName)
        {
            Id = new global::SpacetimeDB.IxCol<MediaSettings, uint>(tableName, "id");
        }
    }
}
