// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.BSATN;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteTables
    {
        public sealed class UserVolumeSettingsHandle : RemoteTableHandle<EventContext, UserVolumeSettings>
        {
            protected override string RemoteTableName => "user_volume_settings";

            public sealed class IdUniqueIndex : UniqueIndexBase<uint>
            {
                protected override uint GetKey(UserVolumeSettings row) => row.Id;

                public IdUniqueIndex(UserVolumeSettingsHandle table) : base(table) { }
            }

            public readonly IdUniqueIndex Id;

            public sealed class ByUserIndex : BTreeIndexBase<SpacetimeDB.Identity>
            {
                protected override SpacetimeDB.Identity GetKey(UserVolumeSettings row) => row.UserId;

                public ByUserIndex(UserVolumeSettingsHandle table) : base(table) { }
            }

            public readonly ByUserIndex ByUser;

            internal UserVolumeSettingsHandle(DbConnection conn) : base(conn)
            {
                Id = new(this);
                ByUser = new(this);
            }

            protected override object GetPrimaryKey(UserVolumeSettings row) => row.Id;
        }

        public readonly UserVolumeSettingsHandle UserVolumeSettings;
    }

    public sealed class UserVolumeSettingsCols
    {
        public global::SpacetimeDB.Col<UserVolumeSettings, uint> Id { get; }
        public global::SpacetimeDB.Col<UserVolumeSettings, SpacetimeDB.Identity> UserId { get; }
        public global::SpacetimeDB.Col<UserVolumeSettings, SpacetimeDB.Identity> TargetUserId { get; }
        public global::SpacetimeDB.Col<UserVolumeSettings, byte> Volume { get; }

        public UserVolumeSettingsCols(string tableName)
        {
            Id = new global::SpacetimeDB.Col<UserVolumeSettings, uint>(tableName, "id");
            UserId = new global::SpacetimeDB.Col<UserVolumeSettings, SpacetimeDB.Identity>(tableName, "user_id");
            TargetUserId = new global::SpacetimeDB.Col<UserVolumeSettings, SpacetimeDB.Identity>(tableName, "target_user_id");
            Volume = new global::SpacetimeDB.Col<UserVolumeSettings, byte>(tableName, "volume");
        }
    }

    public sealed class UserVolumeSettingsIxCols
    {
        public global::SpacetimeDB.IxCol<UserVolumeSettings, uint> Id { get; }
        public global::SpacetimeDB.IxCol<UserVolumeSettings, SpacetimeDB.Identity> UserId { get; }

        public UserVolumeSettingsIxCols(string tableName)
        {
            Id = new global::SpacetimeDB.IxCol<UserVolumeSettings, uint>(tableName, "id");
            UserId = new global::SpacetimeDB.IxCol<UserVolumeSettings, SpacetimeDB.Identity>(tableName, "user_id");
        }
    }
}
