// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.BSATN;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteTables
    {
        public sealed class UserAudioSettingsHandle : RemoteTableHandle<EventContext, UserAudioSettings>
        {
            protected override string RemoteTableName => "user_audio_settings";

            public sealed class UserIdUniqueIndex : UniqueIndexBase<SpacetimeDB.Identity>
            {
                protected override SpacetimeDB.Identity GetKey(UserAudioSettings row) => row.UserId;

                public UserIdUniqueIndex(UserAudioSettingsHandle table) : base(table) { }
            }

            public readonly UserIdUniqueIndex UserId;

            internal UserAudioSettingsHandle(DbConnection conn) : base(conn)
            {
                UserId = new(this);
            }

            protected override object GetPrimaryKey(UserAudioSettings row) => row.UserId;
        }

        public readonly UserAudioSettingsHandle UserAudioSettings;
    }

    public sealed class UserAudioSettingsCols
    {
        public global::SpacetimeDB.Col<UserAudioSettings, SpacetimeDB.Identity> UserId { get; }
        public global::SpacetimeDB.NullableCol<UserAudioSettings, string> InputDeviceId { get; }
        public global::SpacetimeDB.NullableCol<UserAudioSettings, string> OutputDeviceId { get; }
        public global::SpacetimeDB.Col<UserAudioSettings, byte> MicrophoneVolume { get; }
        public global::SpacetimeDB.Col<UserAudioSettings, byte> OutputVolume { get; }
        public global::SpacetimeDB.Col<UserAudioSettings, byte> MicSensitivity { get; }
        public global::SpacetimeDB.Col<UserAudioSettings, bool> HearSelf { get; }

        public UserAudioSettingsCols(string tableName)
        {
            UserId = new global::SpacetimeDB.Col<UserAudioSettings, SpacetimeDB.Identity>(tableName, "user_id");
            InputDeviceId = new global::SpacetimeDB.NullableCol<UserAudioSettings, string>(tableName, "input_device_id");
            OutputDeviceId = new global::SpacetimeDB.NullableCol<UserAudioSettings, string>(tableName, "output_device_id");
            MicrophoneVolume = new global::SpacetimeDB.Col<UserAudioSettings, byte>(tableName, "microphone_volume");
            OutputVolume = new global::SpacetimeDB.Col<UserAudioSettings, byte>(tableName, "output_volume");
            MicSensitivity = new global::SpacetimeDB.Col<UserAudioSettings, byte>(tableName, "mic_sensitivity");
            HearSelf = new global::SpacetimeDB.Col<UserAudioSettings, bool>(tableName, "hear_self");
        }
    }

    public sealed class UserAudioSettingsIxCols
    {
        public global::SpacetimeDB.IxCol<UserAudioSettings, SpacetimeDB.Identity> UserId { get; }

        public UserAudioSettingsIxCols(string tableName)
        {
            UserId = new global::SpacetimeDB.IxCol<UserAudioSettings, SpacetimeDB.Identity>(tableName, "user_id");
        }
    }
}
