// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.BSATN;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteTables
    {
        public sealed class VideoFrameEventHandle : RemoteEventTableHandle<EventContext, VideoFrameEvent>
        {
            protected override string RemoteTableName => "video_frame_event";

            internal VideoFrameEventHandle(DbConnection conn) : base(conn)
            {
            }
        }

        public readonly VideoFrameEventHandle VideoFrameEvent;
    }

    public sealed class VideoFrameEventCols
    {
        public global::SpacetimeDB.Col<VideoFrameEvent, SpacetimeDB.Uuid> SessionId { get; }
        public global::SpacetimeDB.Col<VideoFrameEvent, SpacetimeDB.Identity> From { get; }
        public global::SpacetimeDB.Col<VideoFrameEvent, SpacetimeDB.Identity> To { get; }
        public global::SpacetimeDB.Col<VideoFrameEvent, uint> Seq { get; }
        public global::SpacetimeDB.Col<VideoFrameEvent, ushort> Width { get; }
        public global::SpacetimeDB.Col<VideoFrameEvent, ushort> Height { get; }
        public global::SpacetimeDB.Col<VideoFrameEvent, System.Collections.Generic.List<byte>> Jpeg { get; }

        public VideoFrameEventCols(string tableName)
        {
            SessionId = new global::SpacetimeDB.Col<VideoFrameEvent, SpacetimeDB.Uuid>(tableName, "session_id");
            From = new global::SpacetimeDB.Col<VideoFrameEvent, SpacetimeDB.Identity>(tableName, "from");
            To = new global::SpacetimeDB.Col<VideoFrameEvent, SpacetimeDB.Identity>(tableName, "to");
            Seq = new global::SpacetimeDB.Col<VideoFrameEvent, uint>(tableName, "seq");
            Width = new global::SpacetimeDB.Col<VideoFrameEvent, ushort>(tableName, "width");
            Height = new global::SpacetimeDB.Col<VideoFrameEvent, ushort>(tableName, "height");
            Jpeg = new global::SpacetimeDB.Col<VideoFrameEvent, System.Collections.Generic.List<byte>>(tableName, "jpeg");
        }
    }

    public sealed class VideoFrameEventIxCols
    {

        public VideoFrameEventIxCols(string tableName)
        {
        }
    }
}
