// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.BSATN;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteTables
    {
        public sealed class VoiceChannelMemberHandle : RemoteTableHandle<EventContext, VoiceChannelMember>
        {
            protected override string RemoteTableName => "voice_channel_member";

            public sealed class ByChannelIndex : BTreeIndexBase<uint>
            {
                protected override uint GetKey(VoiceChannelMember row) => row.ChannelId;

                public ByChannelIndex(VoiceChannelMemberHandle table) : base(table) { }
            }

            public readonly ByChannelIndex ByChannel;

            public sealed class UserIdUniqueIndex : UniqueIndexBase<SpacetimeDB.Identity>
            {
                protected override SpacetimeDB.Identity GetKey(VoiceChannelMember row) => row.UserId;

                public UserIdUniqueIndex(VoiceChannelMemberHandle table) : base(table) { }
            }

            public readonly UserIdUniqueIndex UserId;

            internal VoiceChannelMemberHandle(DbConnection conn) : base(conn)
            {
                ByChannel = new(this);
                UserId = new(this);
            }

            protected override object GetPrimaryKey(VoiceChannelMember row) => row.UserId;
        }

        public readonly VoiceChannelMemberHandle VoiceChannelMember;
    }

    public sealed class VoiceChannelMemberCols
    {
        public global::SpacetimeDB.Col<VoiceChannelMember, SpacetimeDB.Identity> UserId { get; }
        public global::SpacetimeDB.Col<VoiceChannelMember, uint> ChannelId { get; }
        public global::SpacetimeDB.Col<VoiceChannelMember, bool> IsMuted { get; }
        public global::SpacetimeDB.Col<VoiceChannelMember, bool> IsDeafened { get; }
        public global::SpacetimeDB.Col<VoiceChannelMember, SpacetimeDB.Timestamp> JoinedAt { get; }

        public VoiceChannelMemberCols(string tableName)
        {
            UserId = new global::SpacetimeDB.Col<VoiceChannelMember, SpacetimeDB.Identity>(tableName, "user_id");
            ChannelId = new global::SpacetimeDB.Col<VoiceChannelMember, uint>(tableName, "channel_id");
            IsMuted = new global::SpacetimeDB.Col<VoiceChannelMember, bool>(tableName, "is_muted");
            IsDeafened = new global::SpacetimeDB.Col<VoiceChannelMember, bool>(tableName, "is_deafened");
            JoinedAt = new global::SpacetimeDB.Col<VoiceChannelMember, SpacetimeDB.Timestamp>(tableName, "joined_at");
        }
    }

    public sealed class VoiceChannelMemberIxCols
    {
        public global::SpacetimeDB.IxCol<VoiceChannelMember, SpacetimeDB.Identity> UserId { get; }
        public global::SpacetimeDB.IxCol<VoiceChannelMember, uint> ChannelId { get; }

        public VoiceChannelMemberIxCols(string tableName)
        {
            UserId = new global::SpacetimeDB.IxCol<VoiceChannelMember, SpacetimeDB.Identity>(tableName, "user_id");
            ChannelId = new global::SpacetimeDB.IxCol<VoiceChannelMember, uint>(tableName, "channel_id");
        }
    }
}
