// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.BSATN;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteTables
    {
        public sealed class VoiceChannelHandle : RemoteTableHandle<EventContext, VoiceChannel>
        {
            protected override string RemoteTableName => "voice_channel";

            public sealed class IdUniqueIndex : UniqueIndexBase<uint>
            {
                protected override uint GetKey(VoiceChannel row) => row.Id;

                public IdUniqueIndex(VoiceChannelHandle table) : base(table) { }
            }

            public readonly IdUniqueIndex Id;

            internal VoiceChannelHandle(DbConnection conn) : base(conn)
            {
                Id = new(this);
            }

            protected override object GetPrimaryKey(VoiceChannel row) => row.Id;
        }

        public readonly VoiceChannelHandle VoiceChannel;
    }

    public sealed class VoiceChannelCols
    {
        public global::SpacetimeDB.Col<VoiceChannel, uint> Id { get; }
        public global::SpacetimeDB.Col<VoiceChannel, string> Name { get; }
        public global::SpacetimeDB.Col<VoiceChannel, uint> MaxMembers { get; }
        public global::SpacetimeDB.Col<VoiceChannel, SpacetimeDB.Timestamp> CreatedAt { get; }

        public VoiceChannelCols(string tableName)
        {
            Id = new global::SpacetimeDB.Col<VoiceChannel, uint>(tableName, "id");
            Name = new global::SpacetimeDB.Col<VoiceChannel, string>(tableName, "name");
            MaxMembers = new global::SpacetimeDB.Col<VoiceChannel, uint>(tableName, "max_members");
            CreatedAt = new global::SpacetimeDB.Col<VoiceChannel, SpacetimeDB.Timestamp>(tableName, "created_at");
        }
    }

    public sealed class VoiceChannelIxCols
    {
        public global::SpacetimeDB.IxCol<VoiceChannel, uint> Id { get; }

        public VoiceChannelIxCols(string tableName)
        {
            Id = new global::SpacetimeDB.IxCol<VoiceChannel, uint>(tableName, "id");
        }
    }
}
